
SELECT * FROM USERS;
SELECT ID, NAME, CITY FROM USERS WHERE CITY = 'Bengaluru';
SELECT * FROM USERS ORDER BY ID DESC;
SELECT * FROM PRODUCTS WHERE PRICE = 2499;
SELECT * FROM ORDERS WHERE EXPIRES_AT = 1893456000;
SELECT * FROM USERS INNER JOIN ORDERS ON USERS.ID = ORDERS.USER_ID;
SELECT USERS.NAME, ORDERS.AMOUNT FROM USERS INNER JOIN ORDERS ON USERS.ID = ORDERS.USER_ID;
SELECT USERS.NAME, ORDERS.AMOUNT FROM USERS INNER JOIN ORDERS ON USERS.ID = ORDERS.USER_ID WHERE USERS.CITY = 'Mumbai';

